#!/bin/bash
#
#  Sparky Remove Desktop lets you install new user to the system
#  Created by Paweł "pavroo" Pijanowski 2017/Apr/30
#  Copyright 2017 under the GNU GPL2 License
#  Last updated 2017/04/30

# get default's locale file
DEFLOCDIR="/usr/share/sparky/sparky-desktop"
if [ "`cat /etc/default/locale | grep es_AR`" != "" ]; then
. $DEFLOCDIR/es
elif [ "`cat /etc/default/locale | grep fr_FR`" != "" ]; then
. $DEFLOCDIR/fr
elif [ "`cat /etc/default/locale | grep it_IT`" != "" ]; then
. $DEFLOCDIR/it
elif [ "`cat /etc/default/locale | grep ja_JP`" != "" ]; then
. $DEFLOCDIR/ja
elif [ "`cat /etc/default/locale | grep pl_PL`" != "" ]; then
. $DEFLOCDIR/pl
elif [ "`cat /etc/default/locale | grep pt_BR`" != "" ]; then
. $DEFLOCDIR/pt_BR
elif [ "`cat /etc/default/locale | grep pt_PT`" != "" ]; then
. $DEFLOCDIR/pt_PT
else
. $DEFLOCDIR/en
fi

testroot="`whoami`"

if [ "$testroot" != "root" ]
then
	echo "Must be root... Exiting now..."
	exit 1
fi

yad --width=600 --height=450 --window-icon=preferences-desktop-display --image=preferences-desktop-display\
 --image-on-top --icons --read-dir=/usr/lib/sparkydesktop/remove --item-width=100\
 --sort-by-name --center --text="$LOCAL15"\
 --title="$LOCAL15" --no-buttons

exit 0



