#!/bin/bash
#
#  Sparky Add Desktop lets you install new user to the system
#  Created by Paweł "pavroo" Pijanowski 2017/Apr/30
#  Copyright 2017 under the GNU GPL2 License
#  Last updated 2017/12/14

# get default's locale file
DEFLOCDIR="/usr/share/sparky/sparky-desktop"
if [ "`cat /etc/default/locale | grep es_AR`" != "" ]; then
. $DEFLOCDIR/es
elif [ "`cat /etc/default/locale | grep fr_FR`" != "" ]; then
. $DEFLOCDIR/fr
elif [ "`cat /etc/default/locale | grep it_IT`" != "" ]; then
. $DEFLOCDIR/it
elif [ "`cat /etc/default/locale | grep ja_JP`" != "" ]; then
. $DEFLOCDIR/ja
elif [ "`cat /etc/default/locale | grep pl_PL`" != "" ]; then
. $DEFLOCDIR/pl
elif [ "`cat /etc/default/locale | grep pt_BR`" != "" ]; then
. $DEFLOCDIR/pt_BR
elif [ "`cat /etc/default/locale | grep pt_PT`" != "" ]; then
. $DEFLOCDIR/pt_PT
else
. $DEFLOCDIR/en
fi

testroot="`whoami`"

if [ "$testroot" != "root" ]
then
	echo "Must be root... Exiting now..."
	exit 1
fi

# General settings for Yad
YAD="yad"
WINDOWICON="--window-icon=preferences-desktop-display --image=preferences-desktop-display"
READDIR="--read-dir"
DIR="/usr/lib/sparkydesktop"
ITEM="--item-width=100"
TITLE="--always-print-result --dialog-sep --title="
TITLETEXT="$LOCAL6"
PLUG="--plug=234501"
HEIGHT="450"
WIDTH="650"
TABNUM="--tabnum"
IMAGEONTOP="--image-on-top"
ICONS="--icons"
SORT="--sort-by-name"
CENTER="--center"
TAB="--tab"
NOTEBOOK="--notebook"
NOBUTTONS="--no-buttons"
TEXT="--text="
ARCHARM="`uname -m | grep arm`"

# Key to bind the windows
KEY="--key"
YADKEY=234501

if [ "$ARCHARM" != "" ]
then
### show desktops for arm arch only
# Tab 1 Debian
$YAD $PLUG $TABNUM=1 $IMAGEONTOP $ICONS $READDIR=$DIR/inst-arm/debian $ITEM $SORT $CENTER &
# Tab 2 Sparky
$YAD $PLUG $TABNUM=2 $IMAGEONTOP $ICONS $READDIR=$DIR/inst-arm/sparky $ITEM $SORT $CENTER &
# Tab 3 Others/3rd party
$YAD $PLUG $TABNUM=3 $IMAGEONTOP $ICONS $READDIR=$DIR/inst-arm/others $ITEM $SORT $CENTER &

# Read yad window with tabs
$YAD $CENTER $NOTEBOOK $TEXT"$LOCAL6\n\n$LOCAL26" $KEY=$YADKEY $TAB="Debian" $TAB="Sparky" $TAB="$LOCAL25" $TITLE"$TITLETEXT" --height=$HEIGHT --width=$WIDTH $NOBUTTONS $WINDOWICON
	
else

### show desktops for x86 arch
# Tab 1 Debian
$YAD $PLUG $TABNUM=1 $IMAGEONTOP $ICONS $READDIR=$DIR/inst/debian $ITEM $SORT $CENTER &
# Tab 2 Sparky
$YAD $PLUG $TABNUM=2 $IMAGEONTOP $ICONS $READDIR=$DIR/inst/sparky $ITEM $SORT $CENTER &
# Tab 3 Others/3rd party
$YAD $PLUG $TABNUM=3 $IMAGEONTOP $ICONS $READDIR=$DIR/inst/others $ITEM $SORT $CENTER &

# Read yad window with tabs
$YAD $CENTER $NOTEBOOK $TEXT"$LOCAL6\n\n$LOCAL26" $KEY=$YADKEY $TAB="Debian" $TAB="Sparky" $TAB="$LOCAL25" $TITLE"$TITLETEXT" --height=$HEIGHT --width=$WIDTH $NOBUTTONS $WINDOWICON
fi

exit 0
